services:

  daemon:
    image: multica-daemon:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - MULTICA_APP_URL=${MULTICA_APP_URL:-http://localhost:3000}
      - MULTICA_SERVER_URL=${MULTICA_SERVER_URL:-http://localhost:8080}
      - MULTICA_TOKEN=${MULTICA_TOKEN}
      - MULTICA_DAEMON_ID=${MULTICA_DAEMON_ID:-}
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-Multica Daemon}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-daemon@multica.ai}
    volumes:
      - workspaces:/workspaces

volumes:
  workspaces:
