services:

  runtime:
    image: multica-runtime:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MULTICA_APP_URL=${MULTICA_APP_URL:-http://localhost:3000}
      - MULTICA_SERVER_URL=${MULTICA_SERVER_URL:-http://localhost:8080}
      - MULTICA_TOKEN=${MULTICA_TOKEN}
      - MULTICA_DAEMON_ID=${MULTICA_DAEMON_ID}